# Generated by Django 3.2.9 on 2021-11-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_name', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputname',
            old_name='data',
            new_name='text',
        ),
    ]
